# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install all dependencies (including dev) to build the project
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the project (compile TypeScript)
RUN npm run build

# Optionally, remove dev dependencies if needed: npm prune --production

# Expose port 3000 if needed
# EXPOSE 3000

# Run the MCP server
CMD ["node", "build/index.js"]
